# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Packs < Formula
  desc "Agent skill package manager - share and install AI agent skills"
  homepage "https://packs.sh"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tunajam/packs/releases/download/v0.3.1/packs_0.3.1_darwin_amd64.tar.gz"
      sha256 "0b1d0ae200d5317c53e528b3ac89dc415c3253cb42a36bfb46d7cb5622a8fe8a"

      def install
        bin.install "packs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tunajam/packs/releases/download/v0.3.1/packs_0.3.1_darwin_arm64.tar.gz"
      sha256 "28a018e5c07964d37f05ce3ae9c20dd5f19c3c0c511476a5e27b83abeb700daf"

      def install
        bin.install "packs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tunajam/packs/releases/download/v0.3.1/packs_0.3.1_linux_amd64.tar.gz"
      sha256 "bfc7d3ed39a92be26c3a1b07612936d2010f6e8e0dee5e87bcd0bf1b6455b1b2"
      def install
        bin.install "packs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tunajam/packs/releases/download/v0.3.1/packs_0.3.1_linux_arm64.tar.gz"
      sha256 "9e05d6131d9974c78a81480830b72bfea11d56f61b4118644caa4f823c440456"
      def install
        bin.install "packs"
      end
    end
  end

  def caveats
    <<~EOS
      🎒 packs is ready! Try these commands:

        packs                      # Browse packs in TUI
        packs find <query>         # Search for packs
        packs get <name>           # Install a pack
        packs get gh:user/repo/path  # Install from GitHub

      Docs: https://packs.sh
    EOS
  end

  test do
    system "#{bin}/packs", "--version"
  end
end
