# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Packs < Formula
  desc "Agent skill package manager - share and install AI agent skills"
  homepage "https://packs.sh"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tunajam/packs/releases/download/v0.3.2/packs_0.3.2_darwin_amd64.tar.gz"
      sha256 "7f8fd41a52ee4f7d23c6563879e57d2856c05d5d537c88160c896be8ebb4c686"

      def install
        bin.install "packs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tunajam/packs/releases/download/v0.3.2/packs_0.3.2_darwin_arm64.tar.gz"
      sha256 "4cecec428836fd345df6bbcffcd9cf0eed2bccefe0620a0ad4998dbff051f4b5"

      def install
        bin.install "packs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tunajam/packs/releases/download/v0.3.2/packs_0.3.2_linux_amd64.tar.gz"
      sha256 "e7875b362e3a33831d635bac9e718380d2743b067a21f8087d0b841d11f89c48"
      def install
        bin.install "packs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tunajam/packs/releases/download/v0.3.2/packs_0.3.2_linux_arm64.tar.gz"
      sha256 "f3b5a104ad574a830960945bfa771527b581cc2f360fc9f9069c2c1b9747ca5e"
      def install
        bin.install "packs"
      end
    end
  end

  def caveats
    <<~EOS
      🎒 packs is ready! Try these commands:

        packs                      # Browse packs in TUI
        packs find <query>         # Search for packs
        packs get <name>           # Install a pack
        packs get gh:user/repo/path  # Install from GitHub

      Docs: https://packs.sh
    EOS
  end

  test do
    system "#{bin}/packs", "--version"
  end
end
